// Code generated by goctl. DO NOT EDIT.
package types

type CategoryRequest struct {
	Page     string `form:"page"`
	PageSize string `form:"page_size"`
}

type Categoty struct {
	ID     int    `json:"id"`
	Title  string `json:"title"`
	Pid    int    `json:"pid"`
	Status int    `json:"status"`
	Sort   int    `json:"sort"`
}

type CategoryResponse struct {
	List  []Categoty `json:"list"`
	Total int        `json:"total"`
}
