// Code generated by goctl. DO NOT EDIT.
package types

type CategoryListRequest struct {
	Page     string `form:"page"`
	PageSize string `form:"pageSize"`
}

type Categoty struct {
	Id     int    `json:"id,optional"`
	Title  string `json:"title"`  //分类名称
	Pid    int    `json:"pid"`    //上级id
	Status int    `json:"status"` //分类状态 1->开启 2->关闭
	Sort   int    `json:"sort"`   //分类排序
}

type CategoryListResponse struct {
	List  []Categoty `json:"list"`  //分类列表
	Total int        `json:"total"` //总数
}

type CategotyCreateRequest struct {
	Categoty
}

type CategotyUpdateRequest struct {
	Categoty
}

type AdminListRequest struct {
	Page     string `form:"page"`
	PageSize string `form:"pageSize"`
}

type AdminBase struct {
	Id       int    `json:"id,optional"`
	Nickname string `json:"nickname"` //昵称
	Account  string `json:"account"`  //登录账号
	Mobile   string `json:"mobile"`   //手机
	Status   int    `json:"status"`   //状态 1->可用 2->禁用
}

type Admin struct {
	AdminBase
	LoginIp   string `json:"login_ip"`   //登录ip
	LoginAt   string `json:"login_at"`   //登录时间
	CreatedAt string `json:"create_at"`  //创建时间
	UpdatedAt string `json:"updated_at"` //修改时间
}

type AdminListResponse struct {
	List  []Admin `json:"list"`  //列表
	Total int     `json:"total"` //总数
}

type AdminCreateRequest struct {
	AdminBase
}

type AdminUpdateRequest struct {
	AdminBase
}
